Delete empty sessions
LBBO/stream-together pull request #30
Opened 2020-10-11 11:17 UTC by s-gbz

Closes #14 

# Previous behaviour:
![session-not-closing](https://user-images.githubusercontent.com/23424538/95677180-06c4fa00-0bc4-11eb-8de6-636c5870c598.PNG)

# New behaviour:
![sessions-closing-if-empty](https://user-images.githubusercontent.com/23424538/95677182-0a588100-0bc4-11eb-8530-3d44a9004979.PNG)

2020-10-18 13:06 UTC, LBBO requested changes
Thank you for your PR! All in all, it's awesome and exactly what I was hoping for. I have two minor issues though that I'd like fixed before merging.

2020-10-18 13:06 UTC, LBBO commented on src/server/Session.ts
> +    console.log(`Session ${sessionID} is now empty. Waiting ${EMPTY_SESSION_TIMEOUT} seconds for potential re-joins before deleting it`)
This console.log statement is no longer accurate, as the session might have just been created (so it isn't suddenly empty and we aren't waiting for re-joins but rather initial joins). I would probably add an optional parameter to toggle between two messages here.

2020-10-18 13:06 UTC, LBBO commented on src/server/SessionManager/SessionManager.ts
> +    // Only send ping if socket hasn't closed in the mean time
Thanks for catching that one :D

2020-10-18 13:06 UTC, LBBO commented on src/server/Session.ts
> +const EMPTY_SESSION_TIMEOUT = 90
I think there should be either a comment or a different variable name here to clarify the timeout is in seconds, not milliseconds. Just to be extra clear

2020-10-19 09:40 UTC, s-gbz commented
I thought about it and suggest to handle the session closing in respective cases.
Benefits:
- Testability
- Readability
- Expandability

Don't get me started how the *function might have looked if it was left joined. I hope this works, feel free to add further suggestions!

2020-10-19 10:24 UTC, LBBO approved these changes

2020-10-19 10:26 UTC, LBBO commented
Perfect. Thank you for your work!

2020-10-19 10:26 UTC, merged